### ISSUE TITLE
Compilation and installation should be cleared/fixed

### ISSUE THREAD

**Issue by akiross** [snap-stanford/ringo#2]
Hello,
I am trying to use ringo on Fedora, I compiled successfully snap and snap-dev, but I cannot `make all` (in fact, I cannot `make anything`) in ringo.

Apparently, the `swig/Makefile` needs a `GITDIR` to be set (you should document this, I didn't find anything about it), which looks like the directory cloned by `git clone https://github.com/snap-stanford/snap`, but it is not, because some header files are missing, e.g.

```
snap.i:184: Error: Unable to find 'predicate.h'
```

I found out that this header file is present in snap-dev, but not in snap, so I modified GITDIR to point to snap-dev. This didn't fix though, I noticed that some files weren't found, again:

```
snap.i:189: Error: Unable to find 'hashgenericmp.h'
```

which is in `snap-dev/glib-adv`, which is not included in the ringo/swig/Makefile `SNAPDIRLIST` variable. I proceeded adding it in a pretty hackish way `-I$(GITDIR)/$(GLIBADV)` and now the header seems to work. 

A new problem arises: `pneanet.i:116: Error: Template 'GetPageRankMP1' undefined.` and others on the same line. The target will fail, compilation will stop.

Everything feels a little too messy and hackish, a sequence of error-fix-error-fix-error makes me think that something more basic is missing.

Could you please provide a little more info on the building and packaging process?
That would be very helpful.

Thanks in advance

**Comment by roks** [comment]
Hi,

We are in the process of making some major updates to snap and snap-dev, which temporarily broke ringo make. We plan to finalize those changes and fix ringo make by the end of January.

**Comment by akiross** [comment]
Ok, but can you at least provide a tag or a commit version which is not broken and is expected to compile? We would like to use ringo for research, and waiting till January is a no-no.

**Comment by roks** [comment]
The last stable release is available for download: http://snap.stanford.edu/ringo/. I suggest that you contact me directly for additional questions: rok@cs.stanford.edu. Thanks!

**Comment by roks** [comment]
We updated the code so that it now compiles on Linux. Clone https://github.com/snap-stanford/snap-dev and https://github.com/snap-stanford/ringo in two parallel directories. Then use 'make' in ringo/swig.

**Comment by akiross** [comment]
Thank you very much, it works now!
