### ISSUE TITLE
Attributes in Ringo work - but return error. Snap Attributes work perfectly

### ISSUE THREAD

**Issue by Tusharsb** [snap-stanford/ringo#6]
I tried running [ringo/test-snappy/attributes.py](https://github.com/snap-stanford/ringo/blob/master/test-snappy/attributes.py) on my Ubuntu 16.04 and it worked pretty good. However I want to use Ringo - not Snap so that I can leverage the multi-core feature of Ringo.

So I replaced 'snap' code with 'ringo' code in attributes.py. See my [attributes_ringo.py.txt](https://github.com/snap-stanford/ringo/files/1183101/attributes_ringo.py.txt)
 file. The output still comes fine, **however the last 2 lines in output show an error message**
```
node 0, NValInt 0, NValFlt 0.00, NValStr 0
edge 0 (0,1), EValInt 0
edge 1 (0,2), EValInt 1
edge 2 (0,3), EValInt 2
...
...
...several lines of output here...truncated
...
...
edge 86 (9,5), EValInt 86
edge 87 (9,6), EValInt 87
edge 88 (9,7), EValInt 88
edge 89 (9,8), EValInt 89
terminate called after throwing an instance of 'TPt<TExcept>'
[1]    8647 abort (core dumped)  python attributes_ringo.py
```
Am I doing something wrong ? Is there a more verbose error output of Ringo/Snap ?

**Comment by roks** [comment]
Most of the Ringo functionality has been integrated to SNAP, including multi-core processing features. I suggest that you use SNAP or Snap.py. We released version 4.0 last week.
